name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install bevy dependenncies
        run: sudo apt-get install libasound2-dev

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose --release

  doc:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: cargo doc --no-deps --document-private-items --workspace

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/doc
